# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.SourceVersion)'

steps:

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: Docker@2
  displayName: Build and push an image
  inputs:
    containerRegistry: 'dockerhub-mcntrn'
    repository: 'mcntrn/flashchat-ui'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(shortversion)'
